# Generated by Django 5.2.10 on 2026-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-created_at',), 'verbose_name': 'O\x9dU,USUæ U.U,O\x15U,', 'verbose_name_plural': 'O\x15U,O\x9dU,USUæ O\x15U,U.U,O\x15U,O\x15OŚ'},
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(verbose_name='O\x15U,U.O-OŚU^U%'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='O\x15U,O"OñUSO_ O\x15U,O\x9dU,UŸO¦OñU^U+US'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name="O§USOñ O¦U. O\x15U,U.U+O'Oñ"),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(max_length=120, verbose_name='O\x15U,O\x15O3U.'),
        ),
    ]
