# Generated by Django 5.2.10 on 2026-01-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_options_alter_blogcomment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('name',), 'verbose_name': 'تصنيف المدونة', 'verbose_name_plural': 'تصنيفات المدونة'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-created_at',), 'verbose_name': 'تعليق', 'verbose_name_plural': 'التعليقات'},
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='مقبول للنشر'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(max_length=120, verbose_name='اسم المعلق'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='المقال'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='نبذة مختصرة'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان المقال'),
        ),
    ]
