# Generated by Django 5.2.10 on 2026-01-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_seo_fields_page_status_contactmessage_status_mediafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'سجل النشاط', 'verbose_name_plural': 'سجل النشاط'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'معلومات التواصل', 'verbose_name_plural': 'معلومات التواصل'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'وسائط', 'verbose_name_plural': 'مكتبة الوسائط'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
    ]
