# Generated by Django 5.2.10 on 2026-01-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_handled',
            field=models.BooleanField(default=False, verbose_name='Handled'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service_type',
            field=models.CharField(choices=[('web', 'Web development'), ('mobile', 'Mobile apps'), ('erp', 'ERP/CRM'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('resolved', 'Closed')], default='new', max_length=20),
        ),
    ]
