# Generated by Django 5.2.10 on 2026-01-31 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=150, verbose_name='Ø§Ø³Ù… Ø§Ù„Ù\x81Ø¦Ø© (Ø¹Ø±Ø¨ÙŠ)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Category name (EN)')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Ù\x81Ø¦Ø© Ø¨Ø§Ù‚Ø§Øª',
                'verbose_name_plural': 'Ù\x81Ø¦Ø§Øª Ø§Ù„Ø¨Ø§Ù‚Ø§Øª',
                'ordering': ('name_ar',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title_ar', models.CharField(max_length=200, verbose_name='Ø§Ù„Ø¹Ù†ÙˆØ§Ù† Ø¨Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('short_description_ar', models.CharField(blank=True, max_length=255, verbose_name='ÙˆØµÙ\x81 Ù‚ØµÙŠØ± (Ø¹Ø±Ø¨ÙŠ)')),
                ('short_description_en', models.CharField(blank=True, max_length=255, verbose_name='Short description (EN)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Ø§Ù„Ù…Ø²Ø§ÙŠØ§ / Ø§Ù„Ù…Ø\xadØªÙˆÙ‰ (Ø¹Ø±Ø¨ÙŠ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Features / content (EN)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ø§Ù„Ø³Ø¹Ø±')),
                ('price_note', models.CharField(blank=True, max_length=120, verbose_name='Ù…Ù„Ø§Ø\xadØ¸Ø© Ø§Ù„Ø³Ø¹Ø±')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='Ø§Ù„Ø¹Ù…Ù„Ø©')),
                ('product_type', models.CharField(choices=[('service', 'Ø®Ø¯Ù…Ø©'), ('bundle', 'Ø¨Ø§Ù‚Ø©')], default='service', max_length=20)),
                ('featured', models.BooleanField(default=False, verbose_name='Ù…Ù…ÙŠØ²')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ù\x81Ø¹Ø§Ù„')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagecategory', verbose_name='Ø§Ù„ØªØµÙ†ÙŠÙ\x81')),
            ],
            options={
                'verbose_name': 'Ø¨Ø§Ù‚Ø©',
                'verbose_name_plural': 'Ø§Ù„Ø¨Ø§Ù‚Ø§Øª',
                'ordering': ('-featured', '-created_at'),
            },
        ),
    ]
