# Generated by Django 5.2.10 on 2026-02-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_seed_package_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-featured', '-created_at'), 'verbose_name': 'باقة', 'verbose_name_plural': 'الباقات'},
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'ordering': ('name_ar',), 'verbose_name': 'فئة باقات', 'verbose_name_plural': 'فئات الباقات'},
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagecategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.CharField(default='SAR', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='المزايا / المحتوى (عربي)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price_note',
            field=models.CharField(blank=True, max_length=120, verbose_name='ملاحظة السعر'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product_type',
            field=models.CharField(choices=[('service', 'خدمة'), ('bundle', 'باقة')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف قصير (عربي)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title_ar',
            field=models.CharField(max_length=200, verbose_name='العنوان بالعربية'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='name_ar',
            field=models.CharField(max_length=150, verbose_name='اسم الفئة (عربي)'),
        ),
    ]
