# Generated by Django 5.2.10 on 2026-01-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_scheduled_publish_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': 'عمل', 'verbose_name_plural': 'الأعمال'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('order',), 'verbose_name': 'صورة عمل', 'verbose_name_plural': 'صور الأعمال'},
        ),
        migrations.AddField(
            model_name='project',
            name='accent_color',
            field=models.CharField(blank=True, max_length=12, verbose_name='لون مساعد'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_font_family',
            field=models.CharField(default='Cairo', max_length=80, verbose_name='خط المحتوى'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_font_size',
            field=models.PositiveSmallIntegerField(default=16, verbose_name='حجم خط النص'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الميزانية (اختياري)'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, default='', verbose_name='التحديات'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='المدة / الجدول الزمني'),
        ),
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.TextField(blank=True, default='', verbose_name='الأهداف'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_color',
            field=models.CharField(blank=True, max_length=12, verbose_name='لون أساسي'),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, default='', verbose_name='النتائج والأثر'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='نطاق العمل'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, default='', verbose_name='الحل'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='ملخص تنفيذي'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='حجم الفريق'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_font_family',
            field=models.CharField(default='Cairo', max_length=80, verbose_name='خط العناوين'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_font_size',
            field=models.PositiveSmallIntegerField(default=28, verbose_name='حجم خط العنوان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'مواقع ويب'), ('mobile', 'تطبيقات جوال'), ('erp', 'أنظمة أعمال / ERP'), ('branding', 'هوية بصرية'), ('other', 'أخرى')], default='web', max_length=50, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='الوصف المختصر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='معرض الصور'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='رابط الكود'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميز في الواجهة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, verbose_name='رابط المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نشر مجدول في'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد التنفيذ'), ('done', 'منجز')], default='done', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology', verbose_name='التقنيات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان العمل'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='التسمية التوضيحية'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='العمل'),
        ),
    ]
