# Generated by Django 5.2.10 on 2026-01-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مشرف عام'), ('manager', 'مدير'), ('editor', 'محرر'), ('viewer', 'مشاهد')], default='viewer', max_length=20),
        ),
    ]
